/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'date' : Time,
  'message' : string,
}
export type AnnouncementId = bigint;
export type ClassId = bigint;
export interface ClassView {
  'id' : ClassId,
  'name' : string,
  'studentIds' : Array<StudentId>,
  'gradeLevel' : bigint,
  'teacherId' : TeacherId,
}
export interface FeePayment {
  'id' : FeePaymentId,
  'feesTerm' : string,
  'total' : bigint,
  'studentId' : StudentId,
  'admissionFee' : bigint,
  'date' : string,
  'fine' : bigint,
  'createdAt' : Time,
  'transport' : bigint,
  'deposit' : bigint,
  'others' : bigint,
  'discountInFee' : bigint,
  'uniform' : bigint,
  'books' : bigint,
  'termlyFee' : bigint,
  'dueableBalance' : bigint,
  'artMaterial' : bigint,
  'registrationFee' : bigint,
  'previousBalance' : bigint,
}
export type FeePaymentId = bigint;
export interface SchoolStats {
  'teacherCount' : bigint,
  'totalFeeCollected' : bigint,
  'classCount' : bigint,
  'studentCount' : bigint,
  'announcementCount' : bigint,
}
export interface Student {
  'id' : StudentId,
  'guardianContact' : string,
  'name' : string,
  'gradeLevel' : bigint,
  'registrationNo' : string,
  'className' : string,
  'guardianName' : string,
}
export type StudentId = bigint;
export interface Teacher {
  'id' : TeacherId,
  'name' : string,
  'department' : string,
}
export type TeacherId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudentToClass' : ActorMethod<[ClassId, StudentId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'createAnnouncement' : ActorMethod<[string, string], AnnouncementId>,
  'createClass' : ActorMethod<[string, bigint, TeacherId], ClassId>,
  'createFeePayment' : ActorMethod<
    [
      StudentId,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
    ],
    FeePaymentId
  >,
  'createStudent' : ActorMethod<
    [string, string, bigint, string, string, string],
    StudentId
  >,
  'createTeacher' : ActorMethod<[string, string], TeacherId>,
  'deleteAnnouncement' : ActorMethod<[AnnouncementId], undefined>,
  'deleteClass' : ActorMethod<[ClassId], undefined>,
  'deleteFeePayment' : ActorMethod<[FeePaymentId], undefined>,
  'deleteStudent' : ActorMethod<[StudentId], undefined>,
  'deleteTeacher' : ActorMethod<[TeacherId], undefined>,
  'forceClaimAdmin' : ActorMethod<[], boolean>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllClasses' : ActorMethod<[], Array<ClassView>>,
  'getAllFeePayments' : ActorMethod<[], Array<FeePayment>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getAnnouncement' : ActorMethod<[AnnouncementId], [] | [Announcement]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[ClassId], [] | [ClassView]>,
  'getFeePaymentsByStudent' : ActorMethod<[StudentId], Array<FeePayment>>,
  'getSchoolStats' : ActorMethod<[], SchoolStats>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [Teacher]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeStudentFromClass' : ActorMethod<[ClassId, StudentId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClass' : ActorMethod<[ClassId, string, bigint, TeacherId], undefined>,
  'updateStudent' : ActorMethod<
    [StudentId, string, string, bigint, string, string, string],
    undefined
  >,
  'updateTeacher' : ActorMethod<[TeacherId, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];