/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClassId = IDL.Nat;
export const StudentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnnouncementId = IDL.Nat;
export const TeacherId = IDL.Nat;
export const FeePaymentId = IDL.Nat;
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'date' : Time,
  'message' : IDL.Text,
});
export const ClassView = IDL.Record({
  'id' : ClassId,
  'name' : IDL.Text,
  'studentIds' : IDL.Vec(StudentId),
  'gradeLevel' : IDL.Nat,
  'teacherId' : TeacherId,
});
export const FeePayment = IDL.Record({
  'id' : FeePaymentId,
  'feesTerm' : IDL.Text,
  'total' : IDL.Nat,
  'studentId' : StudentId,
  'admissionFee' : IDL.Nat,
  'date' : IDL.Text,
  'fine' : IDL.Nat,
  'createdAt' : Time,
  'transport' : IDL.Nat,
  'deposit' : IDL.Nat,
  'others' : IDL.Nat,
  'discountInFee' : IDL.Nat,
  'uniform' : IDL.Nat,
  'books' : IDL.Nat,
  'termlyFee' : IDL.Nat,
  'dueableBalance' : IDL.Nat,
  'artMaterial' : IDL.Nat,
  'registrationFee' : IDL.Nat,
  'previousBalance' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'guardianContact' : IDL.Text,
  'name' : IDL.Text,
  'gradeLevel' : IDL.Nat,
  'registrationNo' : IDL.Text,
  'className' : IDL.Text,
  'guardianName' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SchoolStats = IDL.Record({
  'teacherCount' : IDL.Nat,
  'totalFeeCollected' : IDL.Nat,
  'classCount' : IDL.Nat,
  'studentCount' : IDL.Nat,
  'announcementCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudentToClass' : IDL.Func([ClassId, StudentId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdmin' : IDL.Func([], [IDL.Bool], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [AnnouncementId], []),
  'createClass' : IDL.Func([IDL.Text, IDL.Nat, TeacherId], [ClassId], []),
  'createFeePayment' : IDL.Func(
      [
        StudentId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [FeePaymentId],
      [],
    ),
  'createStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [StudentId],
      [],
    ),
  'createTeacher' : IDL.Func([IDL.Text, IDL.Text], [TeacherId], []),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'deleteClass' : IDL.Func([ClassId], [], []),
  'deleteFeePayment' : IDL.Func([FeePaymentId], [], []),
  'deleteStudent' : IDL.Func([StudentId], [], []),
  'deleteTeacher' : IDL.Func([TeacherId], [], []),
  'forceClaimAdmin' : IDL.Func([], [IDL.Bool], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllClasses' : IDL.Func([], [IDL.Vec(ClassView)], ['query']),
  'getAllFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAnnouncement' : IDL.Func(
      [AnnouncementId],
      [IDL.Opt(Announcement)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([ClassId], [IDL.Opt(ClassView)], ['query']),
  'getFeePaymentsByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(FeePayment)],
      ['query'],
    ),
  'getMyClass' : IDL.Func([], [IDL.Opt(ClassView)], ['query']),
  'getMyStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getMyTeacherId' : IDL.Func([], [IDL.Opt(TeacherId)], ['query']),
  'getSchoolStats' : IDL.Func([], [SchoolStats], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
  'getTeacherByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Teacher)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkTeacherLogin' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'removeStudentFromClass' : IDL.Func([ClassId, StudentId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClass' : IDL.Func([ClassId, IDL.Text, IDL.Nat, TeacherId], [], []),
  'updateStudent' : IDL.Func(
      [StudentId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTeacher' : IDL.Func([TeacherId, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClassId = IDL.Nat;
  const StudentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnnouncementId = IDL.Nat;
  const TeacherId = IDL.Nat;
  const FeePaymentId = IDL.Nat;
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'date' : Time,
    'message' : IDL.Text,
  });
  const ClassView = IDL.Record({
    'id' : ClassId,
    'name' : IDL.Text,
    'studentIds' : IDL.Vec(StudentId),
    'gradeLevel' : IDL.Nat,
    'teacherId' : TeacherId,
  });
  const FeePayment = IDL.Record({
    'id' : FeePaymentId,
    'feesTerm' : IDL.Text,
    'total' : IDL.Nat,
    'studentId' : StudentId,
    'admissionFee' : IDL.Nat,
    'date' : IDL.Text,
    'fine' : IDL.Nat,
    'createdAt' : Time,
    'transport' : IDL.Nat,
    'deposit' : IDL.Nat,
    'others' : IDL.Nat,
    'discountInFee' : IDL.Nat,
    'uniform' : IDL.Nat,
    'books' : IDL.Nat,
    'termlyFee' : IDL.Nat,
    'dueableBalance' : IDL.Nat,
    'artMaterial' : IDL.Nat,
    'registrationFee' : IDL.Nat,
    'previousBalance' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'guardianContact' : IDL.Text,
    'name' : IDL.Text,
    'gradeLevel' : IDL.Nat,
    'registrationNo' : IDL.Text,
    'className' : IDL.Text,
    'guardianName' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SchoolStats = IDL.Record({
    'teacherCount' : IDL.Nat,
    'totalFeeCollected' : IDL.Nat,
    'classCount' : IDL.Nat,
    'studentCount' : IDL.Nat,
    'announcementCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudentToClass' : IDL.Func([ClassId, StudentId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdmin' : IDL.Func([], [IDL.Bool], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [AnnouncementId], []),
    'createClass' : IDL.Func([IDL.Text, IDL.Nat, TeacherId], [ClassId], []),
    'createFeePayment' : IDL.Func(
        [
          StudentId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [FeePaymentId],
        [],
      ),
    'createStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [StudentId],
        [],
      ),
    'createTeacher' : IDL.Func([IDL.Text, IDL.Text], [TeacherId], []),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'deleteClass' : IDL.Func([ClassId], [], []),
    'deleteFeePayment' : IDL.Func([FeePaymentId], [], []),
    'deleteStudent' : IDL.Func([StudentId], [], []),
    'deleteTeacher' : IDL.Func([TeacherId], [], []),
    'forceClaimAdmin' : IDL.Func([], [IDL.Bool], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllClasses' : IDL.Func([], [IDL.Vec(ClassView)], ['query']),
    'getAllFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAnnouncement' : IDL.Func(
        [AnnouncementId],
        [IDL.Opt(Announcement)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([ClassId], [IDL.Opt(ClassView)], ['query']),
    'getFeePaymentsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeePayment)],
        ['query'],
      ),
    'getMyClass' : IDL.Func([], [IDL.Opt(ClassView)], ['query']),
    'getMyStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getMyTeacherId' : IDL.Func([], [IDL.Opt(TeacherId)], ['query']),
    'getSchoolStats' : IDL.Func([], [SchoolStats], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
    'getTeacherByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Teacher)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkTeacherLogin' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'removeStudentFromClass' : IDL.Func([ClassId, StudentId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClass' : IDL.Func([ClassId, IDL.Text, IDL.Nat, TeacherId], [], []),
    'updateStudent' : IDL.Func(
        [StudentId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTeacher' : IDL.Func([TeacherId, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };